title: mold # name of the site
author: Shantanu Mishra # name of site's author
email: dev@8hantanu.net # email of site's author
url: https://8hantanu.net # root address of the site
baseurl: "/mold" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A minimal, optimized, lightweight design for static sites.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: mold # if you are using GitHub Pages, change it to remote_theme: 8hantanu/mold
remote_theme: 8hantanu/mold

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
